proxy:
  webapp-address: 'http://localhost:3000'
  backend-address: 'http://localhost:8080'
server:
  port: 10800
  session:
    cookie:
      name: 'hackathon-proxy'
    timeout: 3600
    persistent: true

